/** @format */

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Puskesmas Hom-Hom Wamena",
  description: "Generated by SmartSpartacuS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="text-color-1 overflow-x-hidden bg-bg-1 bg-cover">
        {children}
      </body>
    </html>
  );
}
